import type { Metadata, Viewport } from 'next'
import { Head } from 'nextra/components'

import './globals.css'
import './fonts.css'

export const viewport: Viewport = Head.viewport

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
